### ISSUE TITLE
Unable to open speedscope flame graph.

### ISSUE THREAD

**Issue by HeenaBansal2009** [laplab/clickhouse-speedscope#1]
Hi, 
I created a speedscope URI  with query-id option in clickhouse using below command
```
heena@Clickhouse1:~/clickhouse-speedscope$ python3 main.py --query-id 0b4a0158-e718-4a22-9940-22b2587a337a
https://www.speedscope.app/#profileURL=http%3A%2F%2Flocalhost%3A8080%2Fquery%3Fquery_id%3D0b4a0158-e718-4a22-9940-22b2587a337a
```
The format which got from main.py is native format, I am getting error when I am importing speedscope app. 
How I can convert my file to json/supported format format

**Comment by laplab** [comment]
Thank you for expressing interest in this project! Unfortunately, I no longer plan to maintain it. A lot might have changed since the publication of this project both in ClickHouse and SpeedScope. I am not aware about the specific problem.
